### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by varundeva** [yakovkhalinsky/backblaze-b2#117]
Trying to upload file
testing in localhost:3000

getting error `connect ECONNREFUSED 127.0.0.1:80` in log

tried by using `axios.defaults.baseURL = "http://localhost:3000/";`
still same problem
anyone have solution?

**Comment by metadaddy** [comment]
@varundeva I [answered a StackOverflow question](https://stackoverflow.com/a/70612597/33905) today along these lines. In that case the error was caused by erroneously passing the `bucketId` in place of the `uploadUrl`. If that wasn't your question, post your code here and I'd be happy to take a look.

**Comment by varundeva** [comment]
In my case i have to upload the .pdf file.
that file already exist in pdf/myfile.pdf . i can provide the path of the file
how can i deal with it

**Comment by varundeva** [comment]
i can able to get the buffer of already stored file using `fs.readFileSync("pdfs/abcd.pdf")`
