### ISSUE TITLE
Return SHA of uploaded file

### ISSUE THREAD

**Issue by mmccallum** [yakovkhalinsky/backblaze-b2#7]
Might not be a bad idea to have the SHA that was generated and used for the upload returned.

**Comment by yakovkhalinsky** [comment]
@mmccallum can do!

I think I could just pass the response JSON back to the success callback of the returned promise, which includes the SHA of the uploaded file.

**Comment by mmccallum** [comment]
I think that would be a perfect place.

**Comment by yakovkhalinsky** [comment]
@mmccallum I just tested this, looks like my generic request and promise generation is always resolving to the JSON body response from the B2 API.

So the current version should work like so:
```
b2.uploadFile(options)
    .then(function(response) {
        console.log('SHA of uploaded file is' + response.contentSha1);
    });
```

**Comment by yakovkhalinsky** [comment]
I have some special cases where I post process the responses that require a small change for me to add the B2 JSON response body.

I'm just looking through my code and so far the following resolve with the JSON response body in the success call back in the `.then()`:
 - all bucket operations
 - b2.uploadFile()
 - b2.listFileNames()
 - b2.listFileVersions()
 - b2.hideFile()
 - b2.getFileInfo()
 - b2.deleteFileVersion()

The rest I will update in the next version so that the promise API is consistent :+1:

**Comment by yakovkhalinsky** [comment]
PR #8 now provides all API responses to success callbacks.
